/**
 * Card SVG URLs from src/assets/cards/*.svg (generated by npm run generate-cards).
 * Outlined is treated as Empty for asset lookup.
 */

const cardModules = import.meta.glob<string>("./*.svg", { query: "?url", eager: true });

function normalizeCardId(cardId: string): string {
  return cardId.replace(/Outlined/g, "Empty");
}

/** Returns the URL for a card SVG, or empty string if not found. */
export function getCardUrl(cardId: string): string {
  const key = `./${normalizeCardId(cardId)}.svg`;
  const value = cardModules[key];
  if (typeof value === "string") return value;
  if (value && typeof value === "object" && "default" in value) return String((value as { default: string }).default);
  return "";
}
